/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DoctorConsultationRouteImport } from './routes/doctor-consultation'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HomeDiagnosticsRouteImport } from './routes/home-diagnostics'
import { Route as LabTestRouteImport } from './routes/lab-test'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PrescriptionRouteImport } from './routes/prescription'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as BookDoctorIdRouteImport } from './routes/book-doctor.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ConsultationIdRouteImport } from './routes/consultation.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as RxIdRouteImport } from './routes/rx.$id'
import { Route as TrackNoRouteImport } from './routes/track.$no'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultationRoute = DoctorConsultationRouteImport.update({
  id: '/doctor-consultation',
  path: '/doctor-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeDiagnosticsRoute = HomeDiagnosticsRouteImport.update({
  id: '/home-diagnostics',
  path: '/home-diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const LabTestRoute = LabTestRouteImport.update({
  id: '/lab-test',
  path: '/lab-test',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionRoute = PrescriptionRouteImport.update({
  id: '/prescription',
  path: '/prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDoctorIdRoute = BookDoctorIdRouteImport.update({
  id: '/book-doctor/$id',
  path: '/book-doctor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationIdRoute = ConsultationIdRouteImport.update({
  id: '/consultation/$id',
  path: '/consultation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RxIdRoute = RxIdRouteImport.update({
  id: '/rx/$id',
  path: '/rx/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackNoRoute = TrackNoRouteImport.update({
  id: '/track/$no',
  path: '/track/$no',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/doctor-consultation': typeof DoctorConsultationRoute
  '/help': typeof HelpRoute
  '/home-diagnostics': typeof HomeDiagnosticsRoute
  '/lab-test': typeof LabTestRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/prescription': typeof PrescriptionRoute
  '/products': typeof ProductsRoute
  '/wishlist': typeof WishlistRoute
  '/book-doctor/$id': typeof BookDoctorIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/consultation/$id': typeof ConsultationIdRoute
  '/product/$id': typeof ProductIdRoute
  '/rx/$id': typeof RxIdRoute
  '/track/$no': typeof TrackNoRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/doctor-consultation': typeof DoctorConsultationRoute
  '/help': typeof HelpRoute
  '/home-diagnostics': typeof HomeDiagnosticsRoute
  '/lab-test': typeof LabTestRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/prescription': typeof PrescriptionRoute
  '/products': typeof ProductsRoute
  '/wishlist': typeof WishlistRoute
  '/book-doctor/$id': typeof BookDoctorIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/consultation/$id': typeof ConsultationIdRoute
  '/product/$id': typeof ProductIdRoute
  '/rx/$id': typeof RxIdRoute
  '/track/$no': typeof TrackNoRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/doctor-consultation': typeof DoctorConsultationRoute
  '/help': typeof HelpRoute
  '/home-diagnostics': typeof HomeDiagnosticsRoute
  '/lab-test': typeof LabTestRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/prescription': typeof PrescriptionRoute
  '/products': typeof ProductsRoute
  '/wishlist': typeof WishlistRoute
  '/book-doctor/$id': typeof BookDoctorIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/consultation/$id': typeof ConsultationIdRoute
  '/product/$id': typeof ProductIdRoute
  '/rx/$id': typeof RxIdRoute
  '/track/$no': typeof TrackNoRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/appointments'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/delivery'
    | '/doctor-consultation'
    | '/help'
    | '/home-diagnostics'
    | '/lab-test'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/prescription'
    | '/products'
    | '/wishlist'
    | '/book-doctor/$id'
    | '/category/$slug'
    | '/consultation/$id'
    | '/product/$id'
    | '/rx/$id'
    | '/track/$no'
    | '/api/public/img/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/appointments'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/delivery'
    | '/doctor-consultation'
    | '/help'
    | '/home-diagnostics'
    | '/lab-test'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/prescription'
    | '/products'
    | '/wishlist'
    | '/book-doctor/$id'
    | '/category/$slug'
    | '/consultation/$id'
    | '/product/$id'
    | '/rx/$id'
    | '/track/$no'
    | '/api/public/img/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/appointments'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/delivery'
    | '/doctor-consultation'
    | '/help'
    | '/home-diagnostics'
    | '/lab-test'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/prescription'
    | '/products'
    | '/wishlist'
    | '/book-doctor/$id'
    | '/category/$slug'
    | '/consultation/$id'
    | '/product/$id'
    | '/rx/$id'
    | '/track/$no'
    | '/api/public/img/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  DeliveryRoute: typeof DeliveryRoute
  DoctorConsultationRoute: typeof DoctorConsultationRoute
  HelpRoute: typeof HelpRoute
  HomeDiagnosticsRoute: typeof HomeDiagnosticsRoute
  LabTestRoute: typeof LabTestRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  OrdersRoute: typeof OrdersRoute
  PrescriptionRoute: typeof PrescriptionRoute
  ProductsRoute: typeof ProductsRoute
  WishlistRoute: typeof WishlistRoute
  BookDoctorIdRoute: typeof BookDoctorIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ConsultationIdRoute: typeof ConsultationIdRoute
  ProductIdRoute: typeof ProductIdRoute
  RxIdRoute: typeof RxIdRoute
  TrackNoRoute: typeof TrackNoRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-consultation': {
      id: '/doctor-consultation'
      path: '/doctor-consultation'
      fullPath: '/doctor-consultation'
      preLoaderRoute: typeof DoctorConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-diagnostics': {
      id: '/home-diagnostics'
      path: '/home-diagnostics'
      fullPath: '/home-diagnostics'
      preLoaderRoute: typeof HomeDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-test': {
      id: '/lab-test'
      path: '/lab-test'
      fullPath: '/lab-test'
      preLoaderRoute: typeof LabTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription': {
      id: '/prescription'
      path: '/prescription'
      fullPath: '/prescription'
      preLoaderRoute: typeof PrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-doctor/$id': {
      id: '/book-doctor/$id'
      path: '/book-doctor/$id'
      fullPath: '/book-doctor/$id'
      preLoaderRoute: typeof BookDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation/$id': {
      id: '/consultation/$id'
      path: '/consultation/$id'
      fullPath: '/consultation/$id'
      preLoaderRoute: typeof ConsultationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rx/$id': {
      id: '/rx/$id'
      path: '/rx/$id'
      fullPath: '/rx/$id'
      preLoaderRoute: typeof RxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$no': {
      id: '/track/$no'
      path: '/track/$no'
      fullPath: '/track/$no'
      preLoaderRoute: typeof TrackNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  DeliveryRoute: DeliveryRoute,
  DoctorConsultationRoute: DoctorConsultationRoute,
  HelpRoute: HelpRoute,
  HomeDiagnosticsRoute: HomeDiagnosticsRoute,
  LabTestRoute: LabTestRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  OrdersRoute: OrdersRoute,
  PrescriptionRoute: PrescriptionRoute,
  ProductsRoute: ProductsRoute,
  WishlistRoute: WishlistRoute,
  BookDoctorIdRoute: BookDoctorIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  ConsultationIdRoute: ConsultationIdRoute,
  ProductIdRoute: ProductIdRoute,
  RxIdRoute: RxIdRoute,
  TrackNoRoute: TrackNoRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
